export const clerkAppearance = {
  layout: {
    socialButtonsPlacement: "bottom" as const,
    showOptionalFields: false,
    shimmer: true,
  },
  elements: {
    rootBox: "w-full max-w-md mx-auto",
    card: "bg-white border-0 shadow-none p-0 w-full rounded-none",
    header: "space-y-1 text-left",
    headerTitle: "text-2xl font-black text-slate-900 tracking-tight",
    headerSubtitle: "text-sm text-slate-500",
    form: "space-y-4",
    formField: "space-y-1.5",
    formFieldLabel: "text-xs font-bold text-slate-600 uppercase tracking-wider",
    formFieldInput: "h-12 w-full px-4 rounded-xl border border-slate-200 bg-slate-50/50 text-slate-900 placeholder-slate-400 focus:bg-white focus:border-blue-500 focus:ring-2 focus:ring-blue-500/10 text-sm transition-all focus:outline-none",
    formButtonPrimary: "w-full h-12 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-md shadow-sm border-0 cursor-pointer transition-all duration-200 active:scale-[0.98] mt-2",
    footerActionText: "text-xs text-slate-500 font-medium",
    footerActionLink: "text-xs text-blue-600 hover:text-blue-700 font-bold decoration-0",
    dividerLine: "bg-slate-100 h-px",
    dividerText: "text-xs text-slate-400 font-medium uppercase px-2",
    identityPreviewText: "text-slate-600 text-sm",
    identityPreviewEditButton: "text-blue-600 hover:text-blue-700 font-semibold text-xs",
    formResendCodeLink: "text-blue-600 hover:text-blue-700 font-semibold text-xs",
    alertText: "text-rose-600 text-xs font-semibold",
    alert: "bg-rose-50 border border-rose-100 rounded-xl p-3 text-rose-900",
    formFieldInputShowPasswordButton: "text-slate-400 hover:text-slate-600 focus:outline-none",
    socialButtonsIconButton: "h-11 rounded-xl border border-slate-200 bg-white hover:bg-slate-50 text-slate-700 font-medium text-sm transition-all shadow-none",
    backLink: "text-xs text-slate-500 font-bold hover:text-slate-800",
  },
};
